name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: thelang-io/setup-the@v1

      - run: sudo apt-get update
      - run: sudo apt-get install build-essential mingw-w64
      - run: sudo sed -e 's/#define _WIN32_WINNT .*/#define _WIN32_WINNT 0x0A00/' -i /usr/share/mingw-w64/include/_mingw.h
      - run: curl -fsSL https://cdn.thelang.io/deps.tar.gz | sudo tar -C /usr/local -xz
      - run: echo "/usr/local/the/osxcross/bin" >> $GITHUB_PATH

      - run: |
          VERSION="${{ github.event.release.tag_name || github.ref }}"
          VERSION="${VERSION#refs/tags/}"
          VERSION="${VERSION:1}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - run: echo $VERSION
      - run: the install
      - run: the compile src/main --platform=linux                 && mv a.out cli-core-linux        && sleep 1
        env:
          THE_DEPS_DIR: /usr/local/the/cross-compile/linux
      - run: the compile src/main --platform=macos   --arch=arm64  && mv a.out cli-core-macos-arm64  && sleep 1
        env:
          THE_DEPS_DIR: /usr/local/the/cross-compile/macos/arm64
      - run: the compile src/main --platform=macos   --arch=x86_64 && mv a.out cli-core-macos-x86_64 && sleep 1
        env:
          THE_DEPS_DIR: /usr/local/the/cross-compile/macos/x86_64
      - run: the compile src/main --platform=windows               && mv a.out cli-core-windows      && sleep 1
        env:
          THE_DEPS_DIR: /usr/local/the/cross-compile/windows
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 cp install.sh            s3://${{ secrets.AWS_S3_BUCKET }}/cli                            --content-type text/plain --content-disposition "attachment;filename=the-install.sh"
      - run: aws s3 cp install.sh            s3://${{ secrets.AWS_S3_BUCKET }}/cli@latest                     --content-type text/plain --content-disposition "attachment;filename=the-install.sh"
      - run: aws s3 cp install.sh            s3://${{ secrets.AWS_S3_BUCKET }}/cli@$VERSION                   --content-type text/plain --content-disposition "attachment;filename=the-install.sh"
      - run: aws s3 cp install.ps1           s3://${{ secrets.AWS_S3_BUCKET }}/cli-win                        --content-type text/plain --content-disposition "attachment;filename=the-install.ps1"
      - run: aws s3 cp install.ps1           s3://${{ secrets.AWS_S3_BUCKET }}/cli-win@latest                 --content-type text/plain --content-disposition "attachment;filename=the-install.ps1"
      - run: aws s3 cp install.ps1           s3://${{ secrets.AWS_S3_BUCKET }}/cli-win@$VERSION               --content-type text/plain --content-disposition "attachment;filename=the-install.ps1"
      - run: aws s3 cp cli-core-linux        s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-linux                 --content-type application/octet-stream
      - run: aws s3 cp cli-core-linux        s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-linux@latest          --content-type application/octet-stream
      - run: aws s3 cp cli-core-linux        s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-linux@$VERSION        --content-type application/octet-stream
      - run: aws s3 cp cli-core-macos-arm64  s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-macos-arm64           --content-type application/octet-stream
      - run: aws s3 cp cli-core-macos-arm64  s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-macos-arm64@latest    --content-type application/octet-stream
      - run: aws s3 cp cli-core-macos-arm64  s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-macos-arm64@$VERSION  --content-type application/octet-stream
      - run: aws s3 cp cli-core-macos-x86_64 s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-macos-x86_64          --content-type application/octet-stream
      - run: aws s3 cp cli-core-macos-x86_64 s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-macos-x86_64@latest   --content-type application/octet-stream
      - run: aws s3 cp cli-core-macos-x86_64 s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-macos-x86_64@$VERSION --content-type application/octet-stream
      - run: aws s3 cp cli-core-windows      s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-windows               --content-type application/octet-stream
      - run: aws s3 cp cli-core-windows      s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-windows@latest        --content-type application/octet-stream
      - run: aws s3 cp cli-core-windows      s3://${{ secrets.AWS_S3_BUCKET }}/cli-core-windows@$VERSION      --content-type application/octet-stream
      - run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} \
            --paths "/cli" "/cli@latest" \
                    "/cli-win" "/cli-win@latest" \
                    "/cli-core-linux" "/cli-core-linux@latest" \
                    "/cli-core-macos-arm64" "/cli-core-macos-arm64@latest" \
                    "/cli-core-macos-x86_64" "/cli-core-macos-x86_64@latest" \
                    "/cli-core-windows" "/cli-core-windows@latest"
