name: Test

on:
  push:
    branches: ['main', 'release-*']
    paths-ignore: ['**/*.md', '**/*.yml', '!.github/workflows/test.yml']
  pull_request:
    paths-ignore: ['**/*.md', '**/*.yml', '!.github/workflows/test.yml']

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-13
          - os: macos-14
          - os: macos-15
          - os: ubuntu-22.04
          - os: ubuntu-24.04
          - os: windows-2019
          - os: windows-2022
          - os: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: thelang-io/setup-the@v1
      - run: the install
      - run: the test test
